services:
  mysql_db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: usama
      MYSQL_PASSWORD: usama123
    restart: always
    networks:
      - app-network
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network
    ports:
      - "8080:80"
    depends_on:
      - mysql_db

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - app-network
    environment:
      MINIO_ROOT_USER: usama
      MINIO_ROOT_PASSWORD: usama123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - mysql_db
      - phpmyadmin
    networks:
      - app-network

volumes:
  mysql-database:
  minio_data:

networks:
  app-network:
    driver: bridge
